### ISSUE TITLE
func_ids option? and dowstream analysis & plotting? 

### ISSUE THREAD

**Issue by marwa38** [gavinmdouglas/FuncDiv#6]
thanks very much for how straightforward to run your code
regarding the comment from R after running `beta_div_contrib()`
what is expected to be in func_ids?

by the way, I didn't get any table outputs from this chunk although I got a directory output, 
Any comments on how I could plot all tables significant functions (each function is in a table). 
![image](https://user-images.githubusercontent.com/68851733/218625154-ef0fe280-698d-4483-9839-a1480f47265b.png)
Is any advice or workflow available on downstream analysis of contributional alpha diversity? (if possible other than STAMP since it hasn't been updated since 2015)
Thanks in advance

**Comment by gavinmdouglas** [comment]
Hi @marwa38,

You can see all the option documentation by typing `?beta_div_contrib`. For `func_ids` it says: `character vector specifying subset of function ids to include for analysis. Will analyze all functions present if this is not specified`, i.e., these are the ids of the functions to use for the analysis.

The function will *either* return an object containing all distance matrices (`return_objects` option), or write them out as files (`write_outfiles` option). This distinction is made because the size of the return object can really be gigantic, and so writing individual tables to the disk separately can be much more memory efficient, depending on how many samples and functions are input.

My personal preference is to conduct data analysis in R using the `ggplot2` package and other great packages like `complexHeatmap`.
