### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by cpavloud** [gavinmdouglas/FuncDiv#8]
Hi! 
I am using R version 4.1.1 and I am trying to install FuncDiv, but it is unsuccessful.

I tried both with 
`library(devtools)
install_github("gavinmdouglas/FuncDiv", ref = "main")`

as well as by downloading release v0.4.2 and building it from source, but in both cases I get the same error
`Error in parseNamespaceFile(package, package.lib, mustExist = FALSE) : 
  unable to re-encode some lines in NAMESPACE file
Calls: <Anonymous> ... withCallingHandlers -> loadNamespace -> parseNamespaceFile
Execution halted
ERROR: lazy loading failed for package FuncDiv removing C:/Program Files/R/R-4.1.1/library/FuncDiv`

Do you have any idea why this is happening?

**Comment by gavinmdouglas** [comment]
Hi @cpavloud,

Thanks for reporting this issue. I'm in the middle of updating FuncDiv and making sure it passes CRAN checks (which _should_ ensure that it installs correctly on Windows). I'm not sure what the problem is at the moment, but I'll notify you once the new version is released (or if I identify a quick fix).

**Comment by gavinmdouglas** [comment]
Hey @cpavloud,

I believe this error should not be resolved in the latest development version!

For details:
After looking into this more I believe this was due to the '^' symbol being interpreted incorrectly on Windows (I think this happened because I copied the relevant line to add to the `NAMESPACE` from a website).

You can see what I mean by the comparison of the old and new lines, where the '^' is clearly different:
<img width="384" alt="Screenshot 2023-03-06 at 5 33 32 PM" src="https://user-images.githubusercontent.com/12489683/223267367-a6a13167-a60e-4afa-9cfd-9d516a98efea.png">

**Comment by cpavloud** [comment]
Oh, wow!
This is one of the errors that can drive a developer crazy...!

Everything is great now, I installed it and it works fine!
Thank you!

**Comment by gavinmdouglas** [comment]
Great to hear! :)
